name: Build Pro

on: [push, workflow_dispatch]

jobs:
  linux-pro:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxext-dev libglu1-mesa-dev libasound2-dev libpulse-dev libaudio-dev libsamplerate0-dev libcurl4-openssl-dev -y

      - name: Build Pro Binary
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_PRO=On -DBUILD_STATIC=ON -DBUILD_WITH_ALL=ON
          cmake --build build --parallel $(nproc)

      - name: Upload Pro Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-linux-pro"
          path: build/bin/tic80
